<a href="https://colab.research.google.com/github/ondology/Training/blob/main/%5BAI_Essential%5D_1%EC%9D%BC%EC%B0%A8_%EC%8B%A4%EC%8A%B5_%EC%BD%94%EB%93%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 01. Python

## 01-001 Python 코드

In [ ]:
# Python: 들여쓰기로 코드 블록 설정
def check_numbers(numbers):
    for number in numbers:
        if number % 2 == 0:
            print(f'{number} is even')
        else:
            print(f'{number} is odd')

# 함수 호출
numbers = [1, 2, 3, 4, 5]
check_numbers(numbers)

1 is odd
2 is even
3 is odd
4 is even
5 is odd


## 01-002 Python: for문을 이용한 시퀀스 순회 구조

In [ ]:
# for문을 이용한 시퀀스 순회 구조
# 시퀀스의 각 요소가 변수에 순차적으로 대입되어 실행 코드가 반복 수행됨
for 변수 in 시퀀스:
    실행할 코드

## 01-003 Python: for문을 이용한 시퀀스 순회 구조

In [ ]:
numbers = [0, 1, 2, 3, 4]  # 리스트 생성

for number in numbers:  # 리스트의 각 요소를 순차적으로 number 변수에 대입
    print(number)  # number의 값을 출력

0
1
2
3
4


## 01-004 Python: range() 함수를 이용한 반복

In [ ]:
# range() 함수를 사용한 반복문
for number in range(5):  # 0부터 4까지의 숫자를 생성하여 number 변수에 대입
    print(number)  # number의 값을 출력

0
1
2
3
4


## 01-005 Python: 함수의 기본 구조

In [ ]:
# 함수 정의 예시
def 함수이름(매개변수1, 매개변수2):
    # 실행할 코드
    return 반환값  # 반환값은 선택 사항

## 01-006 Python: 함수 정의 및 호출

In [ ]:
# 두 값을 더하는 함수 정의
def add(a, b):  # a와 b라는 두 매개변수를 받음
    return a + b  # 두 값을 더한 결과를 반환

# 함수 호출 및 결과 출력
result = add(5, 3)  # add 함수를 호출하여 5와 3을 더한 결과를 반환받음
print(result)  # 결과값 출력 -> 8

8


## 01-007 Python: 기본 매개변수를 사용하는 함수

In [ ]:
# 기본 매개변수를 사용하는 함수 정의
def welcome(name='Guest'):  # 기본값이 'Guest'인 매개변수 name
    return f'Welcome {name}!'  # name 값을 사용해 환영 메시지 반환

# 함수 호출 및 결과 출력
print(welcome())  # 매개변수를 전달하지 않으면 기본값 'Guest'가 사용됨 -> 'Welcome Guest!'
print(welcome('to AI Essential'))  # 'to AI Essential' 값을 전달 -> 'Welcome to AI Essential!'

Welcome Guest!
Welcome to AI Essential!


## 01-008 Python: 모듈 생성 및 사용

In [ ]:
%%writefile mymodule.py
# mymodule.py
def welcome(name='Guest'):
    return f'Welcome {name}!'  # 기본값을 사용하여 환영 메시지 반환

def add(a, b):
    return a + b  # 두 값을 더한 결과를 반환

Writing mymodule.py


## 01-009 Python: 모듈을 사용하여 함수 호출하기

In [ ]:
# mymodule 모듈을 import
import mymodule

# 모듈 내 함수 호출
print(mymodule.welcome('to AI Essential'))  # 'Welcome to AI Essential!' 출력
print(mymodule.add(3, 5))  # 3 + 5 = 8 출력

Welcome to AI Essential!
8


## 01-010 Python: 모듈을 별칭으로 불러오기

In [ ]:
# mymodule 모듈을 별칭 'mm'으로 import
import mymodule as mm

# 모듈의 함수를 별칭을 사용하여 호출
print(mm.welcome('to AI Essential'))  # 'Welcome to AI Essential!' 출력
print(mm.add(3, 5))  # 3 + 5 = 8 출력

Welcome to AI Essential!
8


## 01-011 Python: 모듈에서 특정 함수만 불러오기

In [ ]:
# mymodule 모듈에서 특정 함수만 불러오기
from mymodule import welcome, add

# welcome 함수 호출
print(welcome('to AI Essential'))  # 'Welcome to AI Essential!' 출력

# add 함수 호출
print(add(3, 5))  # 3 + 5 = 8 출력

Welcome to AI Essential!
8


---

# 02. PyTorch Tensor

## 02-001 PyTorch 라이브러리 임포트

In [ ]:
import torch  # PyTorch 라이브러리 임포트

## 02-002 1D 텐서 생성 및 출력

In [ ]:
# 1차원 텐서를 생성 (값: 1.0, 2.0, 3.0)
tensor_1d = torch.tensor([1.0, 2.0, 3.0])
tensor_1d
# 생성된 텐서를 출력 -> tensor([1., 2., 3.])

tensor([1., 2., 3.])

## 02-003 2D 텐서 생성 및 출력

In [ ]:
# 2차원 텐서를 생성 (값: [[1.0, 2.0], [3.0, 4.0]])
tensor_2d = torch.tensor([[1.0, 2.0],
                          [3.0, 4.0]])
tensor_2d
# 생성된 텐서를 출력 ->tensor([[1., 2.],
#                           [3., 4.]])

tensor([[1., 2.],
        [3., 4.]])

## 02-004 텐서를 GPU로 이동

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu' # GPU 사용 가능 여부 확인
tensor_1d = tensor_1d.to(device)  # 1D 텐서 GPU로 이동
tensor_1d.device

device(type='cpu')

## 02-005 텐서 생성 및 dtype 지정

In [ ]:
tensor_1d = torch.tensor([1, 2, 3], dtype=torch.float64)  # dtype을 float64로 지정
tensor_1d  # 텐서 출력 -> tensor([1., 2., 3.], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
tensor_1d = tensor_1d.to(torch.int64)  # dtype을 int64로 지정
tensor_1d  # 텐서 출력 -> tensor([1, 2, 3])

tensor([1, 2, 3])

## 02-006 4차원 텐서의 2차원 변환

In [ ]:
x = torch.randn(10, 64, 7, 7)  # 4차원 텐서 생성: (10, 64, 7, 7)
x.shape

torch.Size([10, 64, 7, 7])

In [ ]:
y = x.reshape(x.shape[0], -1)  # 텐서를 (10, 64 * 7 * 7)으로 변환, 즉 2차원 텐서로 변경
# -1은 나머지 차원을 자동으로 계산하게 하여 (10, 3136)으로 변경
y.shape  # y의 차원은 (10, 3136)

torch.Size([10, 3136])

## 02-007 4차원 텐서의 차원 재배열

In [ ]:
x = torch.randn(10, 28, 28, 3)  # 4차원 텐서 생성: (10, 28, 28, 3)
y = x.permute(0, 3, 1, 2)  # 차원의 순서를 (10, 3, 28, 28)로 재배열
y.shape  # y의 차원은 (10, 3, 28, 28)

torch.Size([10, 3, 28, 28])

## 02-008 1D 텐서에서 요소 선택

In [ ]:
# 1D 텐서 생성
tensor_1d = torch.tensor([10, 20, 30, 40])

# 첫 번째 요소 선택 (Python 인덱스는 0부터 시작)
print(tensor_1d[0]) # 출력: tensor(10)

# 마지막 요소 선택
print(tensor_1d[-1]) # 출력: tensor(40)

tensor(10)
tensor(40)


## 02-009 2D 텐서에서 특정 요소 선택

In [ ]:
# 2D 텐서 생성
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 첫 번째 행, 두 번째 열 요소 선택
print(tensor_2d[0, 1]) # 출력: tensor(2)


# 마지막 행, 마지막 열 요소 선택
print(tensor_2d[-1, -1])# 출력: tensor(9)

tensor(2)
tensor(9)


## 02-010 1D 텐서에서 슬라이싱으로 요소 선택

In [ ]:
# 1D 텐서 생성
tensor_1d = torch.tensor([10, 20, 30, 40, 50])

# 처음부터 인덱스 3까지의 요소 선택
tensor_1d[:4]  # 출력: tensor([10, 20, 30, 40])

tensor([10, 20, 30, 40])

## 02-011 2D 텐서에서 슬라이싱으로 요소 선택

In [ ]:
# 2D 텐서 슬라이싱
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 첫 번째 행 선택
print(tensor_2d[0, :])  # 출력: tensor([1, 2, 3])

# 첫 번째 열 선택
print(tensor_2d[:, 0])  # 출력: tensor([1, 4, 7])

tensor([1, 2, 3])
tensor([1, 4, 7])


## 02-012 1D 텐서에서 특정 요소 수정

In [ ]:
# 1D 텐서 생성
tensor = torch.tensor([10, 20, 30, 40, 50])

# 인덱스 0 위치의 요소 수정
tensor[0] = 100
print(tensor)  # 출력: tensor([100,  20,  30,  40,  50])


# 인덱스 1부터 3까지의 요소 수정
tensor[1:4] = torch.tensor([200, 300, 400])
print(tensor)  # 출력: tensor([100, 200, 300, 400,  50])

tensor([100,  20,  30,  40,  50])
tensor([100, 200, 300, 400,  50])


## 02-013 2D 텐서에서 행의 값 수정

In [ ]:
# 2D 텐서 생성
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 첫 번째 행을 모두 0으로 수정
tensor_2d[0, :] = 0
print(tensor_2d)
# 출력: tensor([[0, 0, 0],
#               [4, 5, 6],
#               [7, 8, 9]])

tensor([[0, 0, 0],
        [4, 5, 6],
        [7, 8, 9]])


## 02-014 요소별 덧셈

In [ ]:
# Tensor 생성
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

# 요소별 덧셈
add_result = x + y  # 또는 torch.add(x, y)
add_result  # 출력: tensor([5, 7, 9])

tensor([5, 7, 9])

## 02-015 브로드캐스팅을 통한 요소별 덧셈

In [ ]:
# Tensor 생성
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
y = torch.tensor([1, 2, 3])

# 브로드캐스팅을 통한 요소별 덧셈
result = x + y
result
# 출력: tensor([[2, 4, 6],
#               [5, 7, 9]])

tensor([[2, 4, 6],
        [5, 7, 9]])

## 02-016 텐서에서 최대값 구하기

In [ ]:
# Tensor 생성
x = torch.tensor([[7, 1, 3],[2, 8, 6],[4, 5, 9]])
# tensor([[7, 1, 3],
#         [2, 8, 6],
#         [4, 5, 9]])

# 모든 요소 중 최대값
print(torch.max(x))  # 출력: tensor(9)

# 특정 차원에서 최대값과 인덱스
print(torch.max(x, dim=1))  # 출력 : torch.return_types.max(values=tensor([7, 8, 9]), indices=tensor([0, 1, 2]))

# 두 Tensor간 원소별 최대 값 반환
print(torch.max(x[0], x[1]))  # 출력 : tensor([7, 8, 6])

tensor(9)
torch.return_types.max(
values=tensor([7, 8, 9]),
indices=tensor([0, 1, 2]))
tensor([7, 8, 6])


## 02-017  텐서에서 합계값 구하기

In [ ]:
# Tensor 생성
x = torch.tensor([[7, 1, 3],[2, 8, 6],[4, 5, 9]])
# tensor([[7, 1, 3],
#         [2, 8, 6],
#         [4, 5, 9]])

# 모든 요소 합
print(torch.sum(x))  # 출력: tensor(45)

# 특정 차원 별 합
print(torch.sum(x, dim=1))  # 출력 : tensor([11, 16, 18])

tensor(45)
tensor([11, 16, 18])


## 연습문제-02-001 1차원 텐서 생성

In [ ]:
# 1차원 텐서 tensor_1d을 0부터 9까지의 정수로 생성
tensor_1d =
tensor_1d  # 생성된 텐서를 출력

## 연습문제-02-002 텐서 속성 확인

In [ ]:
# 1차원 텐서 tensor_1d의 데이터 타입과 할당된 장치, 형태를 확인합니다.
#  dtype, device, shape


## 연습문제-02-003 텐서의 크기 변경

In [ ]:
# 1차원 텐서 tensor_1d의 크기를 2x5로 변경
tensor_2x5 =  # 1차원 텐서를 2x5 텐서로 변경
tensor_2x5

## 연습문제-02-004 텐서에서 최대값과 위치 찾기

In [ ]:
# 모든 요소 중 최대값
print( )  # 출력: tensor(9)

# 특정 차원에서 최대값과 인덱스
print( )  # 출력 : torch.return_types.max(values=tensor([4, 9]), indices=tensor([4, 4]))

# 두 Tensor간 원소별 최대 값 반환
print( )  # 출력 : tensor([5, 6, 7, 8, 9])